server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://consent-poc-eureka-server.cfapps.sap.hana.ondemand.com/eureka
  instance:
    preferIpAddress: false
    hostname: ${vcap.application.uris[0]}
    nonSecurePortEnabled: false
    securePort: 443
    securePortEnabled: true
    statusPageUrl: ${eureka.instance.hostname}/info

spring:
  datasource:
    url: ${vcap.services.DB.credentials.jdbcUrl}
    username: ${vcap.services.DB.credentials.username}
    password: ${vcap.services.DB.credentials.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create