server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: https://consent-poc-eureka-server.cfapps.sap.hana.ondemand.com/eureka
  instance:
    preferIpAddress: false
    hostname: consent-poc-consent-service.cfapps.sap.hana.ondemand.com
    nonSecurePortEnabled: false
    securePort: 443
    securePortEnabled: true
    statusPageUrl: ${eureka.instance.hostname}/info
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${eureka.instance.securePort}}

spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console/